# This is a basic workflow to help you get started with Actions

name: Matrix reporting

# Controls when the workflow will run
on:
  #push:
  #  branches:
  #    - "main"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-repos-for-org:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.MATRIX }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_repos
        with:
          route: GET /orgs/{org}/settings/billing/advanced-security
          org: dsp-testing
          per_page: 100
        env:
          GITHUB_TOKEN: ${{ secrets.APT_TOKEN }}
      - id: set-repos
        run: |
          REPOS=`echo '${{ steps.get_repos.outputs.data }}' | jq '[.repositories[].name]'`
          echo '::set-output name=MATRIX::'$REPOS

  build:
    needs: get-repos-for-org
    strategy:
      fail-fast: false
      matrix:
        repos: ${{fromJson(needs.get-repos-for-org.outputs.repos)}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: amitgupta7/ghas-reports-action@v3.5
      with:
        token: ${{ secrets.APT_TOKEN }}
        # optionally define repo (default is calling repo)
        repo: ${{ matrix.repos }}
        
    - name: Run a one-line script
      run: |
        REPO=${{ matrix.repos }}
        ARTIFACT="${REPO//\//_}"
        echo "::set-output name=ARTIFACT_NAME::$ARTIFACT"
      id: artifact-name
  

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
        path: alerts.xlsx   
           
